### PR TITLE
test(Crawler): Add test using unittest and modify the class `French`

### PR DESCRIPTION
**Pull request by oktak**
#7 
First, I modified class `French` 's `Fetch_Fr()` to single the extraction part and communication with the DB part, such that the unit test can be run independently from a database.

Second, I wrote an unit test case for the extraction part (`fetch_data`), using an example to test against with the result of the function.

### CODE REVIEW

**Comment by oktak** [comment]
Hello @viniciusarre , I have added the flag and the test, also resolved the conflict with master branch. You may review on it.

**Comment by viniciusarre** [comment]
Hello @oktak, thank you for your contribution! I like your approach to the solution! 

I am, however, getting an error when trying to run the code... it seems to be a reference error...
```

ERROR: test_fetch_French (tests.Test_crawler.TestCrawler)
Test quotes, language, author and source
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/whoami/reviews/quote-a-lang-crawler/oktak/quote-a-lang-crawler/tests/Test_crawler.py", line 34, in test_fetch_French
    test_data = testfr.__fetch_fr(soup, url_name, save_to_db=False, data_in=data_init)
AttributeError: 'French' object has no attribute '_TestCrawler__fetch_fr'

----------------------------------------------------------------------
Ran 1 test in 0.862s

```

Could you take a look at this? I tried running it as you commented in the issue... 
`python3 -m unittest tests/Test_crawler.py`

**Comment by oktak** [comment]
Ouch! I didn't realize that the method has become a private method (with two underscore) (since this commit https://github.com/viniciusarre/quote-a-lang-crawler/pull/10/commits/7d4c8929f8d0e1c55ece5954031c925c761075bb), which make it not easy to be accessible from the Test suite.

It's my mistake that I didn't re-run my test once more after the functions name changed.

So, now `__fetch_fr` is called by `url_set_up`, should we test for `url_set_up` instead of testing `__fetch_fr`?

**Comment by viniciusarre** [comment]
Thanks for your comment!

Yes, I think it makes more sense to test it from there, this way we'd test the complete flow, since this flow is replicated in the Tornado server as well (for new author querying, etc.)

Do you think this would be doable? I think `__fetch_fr` ends up making more sense as a private method, in order to keep it in the flow's scope... anyway, I think you'd also need to pass a `save_to_db = true` as a parameter to it, as well as in `__fetch_fr`. 

What do you think, @oktak

**Comment by oktak** [comment]
Thanks @viniciusarre . I acknowledge that `__fetch_fr` to be a private method would be better now. So let's move to the case of testing `url_set_up`.

`url_set_up` has if-branches and involves some side effects: writing data of DB, logging to DB, while return a Boolean value for a status of whether the app has written new data to DB. To me, this is slightly complicated to test it. Or the testing would become not so straight forward.

I think it is doable. What to do is to single out the functional parts, like the code interacts with DB. Passing a `save_to_db = True` is inevitable.

Also for the if-branches, we may also need to consider those different cases. Making multiple testing stages to cover these scenarios, by passing mocking data. Also the return value, may need to change to not only True or False, but also the data from `__fetch_fr`

I'll try.

**Comment by oktak** [comment]
Hello @viniciusarre , here is my try: https://github.com/viniciusarre/quote-a-lang-crawler/pull/11/commits/a6d93c6b52566e08e58684dfef7deb8fdd98547f

Please comment if it is acceptable to change the return value of url_set_up from solely Boolean to a mapping.

**Comment by viniciusarre** [comment]
Hello @oktak, thank you again for your contribution! I have been a bit busy this week, sorry... I will be reviewing your PR in further detail tomorrow! Thanks for your patience!

**Comment by oktak** [comment]
You are welcome. Take your time~

**Comment by viniciusarre** [comment]
Great! Thank you for your contribution, @oktak 

I have reviewed it and I believe it can be merged!

**Pull request merged**
